x-google-marketplace:

  schemaVersion: v2

  applicationApiVersion: v1beta1

  publishedVersion: '1.0.0'
  publishedVersionMetadata:
    releaseNote: >-
      Initial release.
    releaseTypes:
      - Feature
    recommended: true
  
  images: {}

# Temporarily commenting out during development.
#  images:
#    grafana:
#      properties:
#        k8ssandra.kube-prometheus-stack.grafana.image.repository:
#          type: REPO_WITHOUT_REGISTRY
#        k8ssandra.kube-prometheus-stack.grafana.image.tag:
#          type: TAG
#        k8ssandra.kube-prometheus-stack.grafana.initChownData.image.repository:
#          type: REPO_WITHOUT_REGISTRY
#        k8ssandra.kube-prometheus-stack.grafana.initChownData.image.tag:
#          type: TAG
#        k8ssandra.kube-prometheus-stack.grafana.sidecar.image.repository:
#          type: REPO_WITHOUT_REGISTRY
#        k8ssandra.kube-prometheus-stack.grafana.sidecar.image.tag:
#          type: TAG
#        k8ssandra.kube-prometheus-stack.grafana.imageRenderer.image.repository:
#          type: REPO_WITHOUT_REGISTRY
#        k8ssandra.kube-prometheus-stack.grafana.imageRenderer.image.tag:
#          type: TAG
#    kube-state-metrics:
#      properties:
#        k8ssandra.kube-prometheus-stack.kube-state-metrics.image.repository:
#          type: REPO_WITHOUT_REGISTRY
#        k8ssandra.kube-prometheus-stack.kube-state-metrics.image.tag:
#          type: TAG
#    prometheus-node-exporter:
#        k8ssandra.kube-prometheus-stack.prometheus-node-exporter.image.repository:
#          type: REPO_WITHOUT_REGISTRY
#        k8ssandra.kube-prometheus-stack.prometheus-node-exporter.image.tag:
#          type: TAG
#    kube-prometheus-stack:
#      properties:
#        k8ssandra.kube-prometheus-stack.alertmanager.alertmanagerSpec.image.repository:
#          type: REPO_WITHOUT_REGISTRY
#        k8ssandra.kube-prometheus-stack.alertmanager.alertmanagerSpec.image.tag:
#          type: TAG
#        k8ssandra.kube-prometheus-stack.prometheusOperator.image.repository:
#          type: REPO_WITHOUT_REGISTRY
#        k8ssandra.kube-prometheus-stack.prometheusOperator.image.tag:
#          type: TAG
#        k8ssandra.kube-prometheus-stack.prometheusOperator.admissionWebhooks.patch.image.repository:
#          type: REPO_WITHOUT_REGISTRY
#        k8ssandra.kube-prometheus-stack.prometheusOperator.admissionWebhooks.patch.image.tag:
#          type: TAG
#        k8ssandra.kube-prometheus-stack.prometheusOperator.prometheusSpec.image.repository:
#          type: REPO_WITHOUT_REGISTRY
#        k8ssandra.kube-prometheus-stack.prometheusOperator.prometheusSpec.image.tag:
#          type: TAG
#    reaper-operator:
#      properties:
#        k8ssandra.reaper-operator.image.registry:
#          type: REGISTRY
#        k8ssandra.reaper-operator.image.repository:
#          type: REPO_WITHOUT_REGISTRY
#        k8ssandra.reaper-operator.image.tag:
#          type: TAG
#    medusa-operator:
#      properties:
#        k8ssandra.medusa-operator.image.registry:
#          type: REGISTRY
#        k8ssandra.medusa-operator.image.repository:
#          type: REPO_WITHOUT_REGISTRY
#        k8ssandra.medusa-operator.image.tag:
#          type: TAG
#    cass-operator:
#      properties:
#        k8ssandra.cass-operator.image.registry:
#          type: REGISTRY
#        k8ssandra.cass-operator.image.repository:
#          type: REPO_WITHOUT_REGISTRY
#        k8ssandra.cass-operator.image.tag:
#          type: TAG
#    k8ssandra:
#      properties:
#        k8ssandra.cassandra.configBuilder.image.registry:
#          type: REGISTRY
#        k8ssandra.cassandra.configBuilder.image.repository:
#          type: REPO_WITHOUT_REGISTRY
#        k8ssandra.cassandra.configBuilder.image.tag:
#          type: TAG
#        k8ssandra.cassandra.jmxCredentialsConfig.image.registry:
#          type: REGISTRY
#        k8ssandra.cassandra.jmxCredentialsConfig.image.repository:
#          type: REPO_WITHOUT_REGISTRY
#        k8ssandra.cassandra.jmxCredentialsConfig.image.tag:
#          type: TAG
#        k8ssandra.cassandra.loggingSidecar.image.registry:
#          type: REGISTRY
#        k8ssandra.cassandra.loggingSidecar.image.repository:
#          type: REPO_WITHOUT_REGISTRY
#        k8ssandra.cassandra.loggingSidecar.image.tag:
#          type: TAG
#        k8ssandra.stargate.waitForCassandra.image.registry:
#          type: REGISTRY
#        k8ssandra.stargate.waitForCassandra.image.repository:
#          type: REPO_WITHOUT_REGISTRY
#        k8ssandra.stargate.waitForCassandra.image.tag:
#          type: TAG
#        k8ssandra.reaper.image.registry:
#          type: REGISTRY
#        k8ssandra.reaper.image.repository:
#          type: REPO_WITHOUT_REGISTRY
#        k8ssandra.reaper.image.tag:
#          type: TAG
#        k8ssandra.medusa.image.registry:
#          type: REGISTRY
#        k8ssandra.medusa.image.repository:
#          type: REPO_WITHOUT_REGISTRY
#        k8ssandra.medusa.image.tag:
#          type: TAG
#        k8ssandra.cleaner.image.registry:
#          type: REGISTRY
#        k8ssandra.cleaner.image.repository:
#          type: REPO_WITHOUT_REGISTRY
#        k8ssandra.cleaner.image.tag:
#          type: TAG
#        k8ssandra.client.image.registry:
#          type: REGISTRY
#        k8ssandra.client.image.repository:
#          type: REPO_WITHOUT_REGISTRY
#        k8ssandra.client.image.tag:
#          type: TAG

  deployerServiceAccount:
    description: >
      creates application resources
    roles:
    - type: ClusterRole
      rulesType: CUSTOM
      rules:
      - apiGroups: ['admissionregistration.k8s.io','apiextensions.k8s.io','apiregistration.k8s.io','apps','authentication.k8s.io','authorization.k8s.io','batch','certificates.k8s.io','coordination.k8s.io','core','discovery.k8s.io','events.k8s.io','flowcontrol.apiserver.k8s.io','internal.apiserver.k8s.io','networking.k8s.io','node.k8s.io','policy','rbac.authorization.k8s.io','scheduling.k8s.io','storage.k8s.io']
        resources: ['*']
        verbs: ['*']

properties:

  name:
    type: string
    x-google-marketplace:
      type: NAME

  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE

  grafanaServiceAccount:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >
          service account used for the grafana component of k8ssandra
        roles:
          - type: Role
            rulesType: CUSTOM
            rules:
              - apiGroups: ['extensions', '']
                resources: ['podsecuritypolicies', 'secrets', 'configmaps']
                verbs: ['use', 'get', 'list', 'watch']

  cass-operatorServiceAccount:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >
          service account used for the cass-operator component of k8ssandra
        roles:
          - type: Role
            rulesType: CUSTOM
            rules:
              - apiGroups: ['']
                resources: ['pods','services','endpoints','persistentvolumeclaims','events','configmaps','secrets']
                verbs: ['*']
              - apiGroups: ['']
                resources: ['namespaces']
                verbs: ['get']
              - apiGroups: ['apps']
                resources: ['deployments','daemonsets','replicasets','statefulsets']
                verbs: ['*']
              - apiGroups: ['monitoring.coreos.com']
                resources: ['servicemonitors']
                verbs: ['get', 'create']
              - apiGroups: ['apps']
                resources: ['deployments/finalizers']
                verbs: ['update']
              - apiGroups: ['datastax.com']
                resources: ['*']
                verbs: ['*']
              - apiGroups: ['policy']
                resources: ['poddisruptionbudgets']
                verbs: ['*']
              - apiGroups: ['cassandra.datastax.com']
                resources: ['*']
                verbs: ['*']
              - apiGroups: ['batch']
                resources: ['*']
                verbs: ['*']
          - type: ClusterRole
            rulesType: CUSTOM
            rules:
              - apiGroups: ['']
                resources: ['nodes','persistentvolumes']
                verbs: ['get','watch','list']

  kube-promethe-admissionServiceAccount:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >
          service account used for kube-promethe-admission component of k8ssandra
        roles:
          - type: Role
            rulesType: CUSTOM
            rules:
              - apiGroups: ['']
                resources: ['secrets']
                verbs: ['get', 'create']
          - type: ClusterRole
            rulesType: CUSTOM
            rules:
              - apiGroups: ['admissionregistration.k8s.io']
                resources: ['validatingwebhookconfigurations','mutatingwebhookconfigurations']
                verbs: ['get','update']
              - apiGroups: ['policy']
                resources: ['podsecuritypolicies']
                verbs: ['use']

  kube-promethe-operatorServiceAccount:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >
          service account used for the kube-promethe-operator component of k8ssandra
        roles:
          - type: ClusterRole
            rulesType: CUSTOM
            rules:
              - apiGroups: ['monitoring.coreos.com']
                resources: ['alertmanagers','alertmanagers/finalizers','alertmanagerconfigs','prometheuses','prometheuses/finalizers','thanosrulers','thanosrulers/finalizers','servicemonitors','podmonitors','probes','prometheusrules']
                verbs: ['*']
              - apiGroups: ['apps']
                resources: ['statefulsets']
                verbs: ['*']
              - apiGroups: ['']
                resources: ['configmaps','secrets']
                verbs: ['*']
              - apiGroups: ['']
                resources: ['pods']
                verbs: ['list', 'delete']
              - apiGroups: ['']
                resources: ['services','services/finalizers','endpoints']
                verbs: ['get','create','update','delete']
              - apiGroups: ['']
                resources: ['nodes']
                verbs: ['list','watch']
              - apiGroups: ['']
                resources: ['namespaces']
                verbs: ['get','list','watch']
              - apiGroups: ['networking.k8s.io']
                resources: ['ingress']
                verbs: ['get','list','watch']
              - apiGroups: ['policy']
                resources: ['podsecuritypolicies']
                verbs: ['use']

  kube-promethe-prometheusServiceAccount:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >
          service account used for the kube-promethe-prometheus component of k8ssandra
        roles:
          - type: ClusterRole
            rulesType: CUSTOM
            rules:
              - apiGroups: ['']
                resources: ['nodes','nodes/metrics','services','endpoints','pods']
                verbs: ['get','list','watch']
              - apiGroups: ['networking.k8s.io']
                resources: ['ingress']
                verbs: ['get','watch','list']
              - apiGroups: ['policy']
                resources: ['podsecuritypolicies']
                verbs: ['use']

  k8ssandra.cassandra.clusterName:
    type: string
    default: "k8ssandra-mp"
    description: name of the Cassandra cluster

  k8ssandra.cassandra.cassandraLibDirVolume.size:
    type: string
    default: "10Gi"
    description: size of the storage volume for Cassandra

  # It looks like this syntax is not currently supported, so may need
  # some custom parsing magic in the deployer image.
  #k8ssandra.cassandra.datacenters[0].size:
  #  type: integer
  #  default: 4
  #  description: size of the datacenter

    #k8ssandra.cassandra.datacenters[0].name:
    #type: string
    #x-google-marketplace:
    #  type: STRING
    #default: dc1
    #description: name of the datacenter

required:
  - name
  - namespace

