apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: k8ssandra-storage
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  fstype: ext4
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
