admiss-ctrl-image-repository: null
ubbagent-image-repository: null
k8ssandra:
  cassandra:
    version: "4.0.0"
    cassandraLibDirVolume:
      storageClass: k8ssandra-storage
      size: 5Gi
    allowMultipleNodesPerWorker: true
    heap:
      size: 1G
      newGenSize: 1G
    resources:
      requests:
        cpu: 1000m
        memory: 2Gi
      limits:
        cpu: 1000m
        memory: 2Gi
    datacenters:
      - name: dc1
        size: 3
        racks:
          - name: default
  reaper:
    enabled: true
  reaper-operator:
    enabled: true
  stargate:
    enabled: true
    livenessInitialDelaySeconds: "240"
    readinessInitialDelaySeconds: "240"
  kube-prometheus-stack:
    nameOverride: prom
    enabled: true
    alertmanager:
      serviceAccount:
        create: false
    prometheusOperator:
      serviceAccount:
        create: false
    prometheus:
      serviceAccount:
        create: false
  medusa:
    enabled: false
    storage: google_storage
    bucket_name: prod-k8ssandra-mp-storage-bucket
    storageSecret: prod-k8ssandra-mp-medusa-key
    storageCredentialsJSON: ""
