k8ssandra:
  admissionControllerDatastax:
    image:
      repository: gcr.io/gke-launcher-dev/k8ssandra-mp/admission-controller:1.3.1
  cassandra:
    version: "4.0.0"
    cassandraLibDirVolume:
      storageClass: k8ssandra-storage
      size: 1Gi
    allowMultipleNodesPerWorker: true
    heap:
      size: 1G
      newGenSize: 1G
    resources:
      requests:
        cpu: 1000m
        memory: 2Gi
      limits:
        cpu: 1000m
        memory: 2Gi
    datacenters:
      - name: dc1
        size: 3
        racks:
          - name: default
  reaper:
    enabled: true
  reaper-operator:
    enabled: true
  stargate:
    enabled: true
    livenessInitialDelaySeconds: "240"
    readinessInitialDelaySeconds: "240"
  kube-prometheus-stack:
    enabled: true
  medusa:
    enabled: false
    storage: google_storage
    bucket_name: prod-k8ssandra-mp-storage-bucket
    storageSecret: prod-k8ssandra-mp-medusa-key
    storageCredentialsJSON: ""
