apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: ServiceAccount
      name: $NAME-grafana

  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: Role
      name: $NAME-grafana

  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: RoleBinding
      name: $NAME-grafana

  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: ClusterRole
      name: $NAME-grafana-clusterrole

  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: ClusterRoleBinding
      name: $NAME-grafana-clusterrolebinding

  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      name: $NAME-grafana-test

  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: ServiceAccount
      name: $CASS_OPERATOR_ORIG_SA

  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: Role
      name: $NAME-cass-operator

  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: RoleBinding
      name: $NAME-cass-operator

  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: ClusterRole
      name: $NAME-cass-operator-cr

  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: ClusterRoleBinding
      name: $NAME-cass-operator-cr

  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: ServiceAccount
      name: $PROM_NAME-admission

  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: Role
      name: $PROM_NAME-admission

  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: RoleBinding
      name: $PROM_NAME-admission

  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: ClusterRole
      name: $PROM_NAME-admission

  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: ClusterRoleBinding
      name: $PROM_NAME-admission

  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: ServiceAccount
      name: $PROM_NAME-operator

  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: ClusterRole
      name: $PROM_NAME-operator

  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: ClusterRoleBinding
      name: $PROM_NAME-operator

  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: ClusterRole
      name: $PROM_NAME-operator-psp

  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: ClusterRoleBinding
      name: $PROM_NAME-operator-psp

  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: ServiceAccount
      name: $PROM_NAME-prometheus

  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: ClusterRole
      name: $PROM_NAME-prometheus

  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: ClusterRoleBinding
      name: $PROM_NAME-prometheus

  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: ClusterRole
      name: $PROM_NAME-prometheus-psp

  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      kind: ClusterRoleBinding
      name: $PROM_NAME-prometheus-psp

  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      name: $NAME-cleaner-k8ssandra

  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      name: $NAME-cleaner-job-k8ssandra

  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      name: $NAME-crd-upgrader-k8ssandra

  - patch: |-
      - op: replace
        path: /metadata/labels/excluded-resource
        value: "yes"
    target:
      name: $NAME-crd-upgrader-job-k8ssandra

resources:
  - chart.yaml
