apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: $NAME
  excluded-resource: "no"
  is-crd: "no"

patches:

  - patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: "$ADMISS_CTRL_SA"
    target:
      kind: Deployment
      name: "$ADMISS_CTRL_DEPLOYMENT"

  - patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: "$CASS_OPERATOR_SA"
    target:
      kind: Deployment
      name: "$CASS_OPERATOR_DEPLOYMENT"

  - patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: "$WEBHOOK_ADMISS_SA"
    target:
      kind: Job
      name: "$WEBHOOK_ADMISS_CREATE_JOB"

  - patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: "$WEBHOOK_ADMISS_SA"
    target:
      kind: Job
      name: "$WEBHOOK_ADMISS_PATCH_JOB"

  - patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: "$GRAFANA_SA"
    target:
      kind: Deployment
      name: "$GRAFANA_DEPLOYMENT"

  - patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: "$PROM_OPERATOR_SA"
    target:
      kind: Deployment
      name: "$PROM_OPERATOR_DEPLOYMENT"

  - patch: |-
      - op: replace
        path: /spec/serviceAccountName
        value: "$PROMETHEUS_SA"
    target:
      kind: Prometheus
      name: "$PROMETHEUS_DEPLOYMENT"

resources:
  - chart.yaml 
