apiVersion: app.k8s.io/v1beta1

kind: Application

metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
  annotations:
    kubernetes-engine.cloud.google.com/icon: >-
      data:image/png;base64,{{ .Files.Get "logo.png" | b64enc }}
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "datastax-public", "product_id": "k8ssandra-marketplace", "partner_name": "DataStax"}'

spec:
  descriptor:
    type: K8ssandra-marketplace
    version: "4.0.0-k8ssandra1.5.1-cma4.0.0b2"
    description: >-
      Built on the rock-solid Apache Cassandra® NoSQL database, K8ssandra brings together a complete operational data platform for Kubernetes including APIs, monitoring, and backups.
    maintainers:
      - name: DataStax
        url: https://github.com/DSPN/k8ssandra-gcp-mp#readme
    links:
      - description: 'User Guide: K8ssandra-marketplace'
        url: https://github.com/DSPN/k8ssandra-gcp-mp#readme
    notes: |-

      # Wait for the Application components to become available
      It will take about 10 or 15 minutes for all the components of k8ssandra to become fully available and ready to use. You can follow the status of the install process with the following command:

        `watch kubectl get pods --namespace "$NAMESPACE"`

  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}"
  addOwnerRef: true
  componentKinds:
    - group: 'v1'
      kind: PersistentVolumeClaim
    - group: 'v1'
      kind: Service
    - group: 'apps/v1'
      kind: StatefulSet
    - group: 'apiextensions.k8s.io/v1'
      kind: CustomResourceDefinition
    - group: 'policy/v1beta1'
      kind: PodSecurityPolicy
    - group: 'v1'
      kind: ServiceAccount
    - group: 'v1'
      kind: Secret
    - group: 'v1'
      kind: ConfigMap
    - group: 'rbac.authorization.k8s.io/v1'
      kind: ClusterRole
    - group: 'rbac.authorization.k8s.io/v1'
      kind: ClusterRoleBinding
    - group: 'rbac.authorization.k8s.io/v1'
      kind: Role
    - group: 'rbac.authorization.k8s.io/v1'
      kind: RoleBinding
    - group: 'apps/v1'
      kind: Deployment
    - group: 'cassandra.datastax.com/v1beta1'
      kind: CassandraDatacenter
    - group: 'admissionregistration.k8s.io/v1'
      kind: MutatingWebhookConfiguration
    - group: 'admissionregistration.k8s.io/v1'
      kind: ValidatingWebhookConfiguration
    - group: 'monitoring.coreos.com/v1'
      kind: Prometheus
    - group: 'monitoring.coreos.com/v1'
      kind: PrometheusRule
    - group: 'reaper.cassandra-reaper.io/v1alpha1'
      kind: Reaper
    - group: 'monitoring.coreos.com/v1'
      kind: ServiceMonitor
    - group: 'v1'
      kind: Pod
    - group: 'batch/v1'
      kind: Job
